# Generated by Django 5.2.7 on 2025-10-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='product_url',
            field=models.URLField(default='https://mysportsshoe.com/wp-content/uploads/2019/02/806667_01-768x768.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(),
        ),
    ]
