# Generated by Django 5.2.7 on 2025-10-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_store_app', '0003_accessories_remove_shoe_product_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accessories',
            new_name='Accessory',
        ),
    ]
