# Generated by Django 5.2.7 on 2025-10-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_store_app', '0004_rename_accessories_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='accessories',
            field=models.ManyToManyField(to='shoe_store_app.accessory'),
        ),
    ]
