# Generated by Django 5.2.7 on 2025-10-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_store_app', '0005_shoe_accessories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='accessories',
            new_name='accessory',
        ),
    ]
